apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo 
  labels:
    k8s-app: flaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: flaskdemo
  template:
    metadata:
      labels:
        k8s-app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: icr.io/ibmdemo/flaskdemo:v1 
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskdemo
  labels:
    k8s-app: flaskdemo 
spec:
  selector:
    k8s-app: flaskdemo
  type: NodePort
  ports:
   - port: 5000